/* i18n.js — DataEngineered language suggestion. Generated by scripts/i18n_common.py; do not edit.
   Suggests the visitor's language when this page has it. Never redirects; remembers a choice. */
(function () {
  'use strict';
  var KEY = 'de-lang-choice';
  var MSG = {
    'en': ['This page is also available in English.', 'Read in English', 'Close'],
    'es': ['Esta página también está disponible en español.', 'Leer en español', 'Cerrar'],
    'de': ['Diese Seite ist auch auf Deutsch verfügbar.', 'Auf Deutsch lesen', 'Schließen'],
    'fr': ['Cette page est aussi disponible en français.', 'Lire en français', 'Fermer'],
    'pt-br': ['Esta página também está disponível em português.', 'Ler em português', 'Fechar'],
    'it': ['Questa pagina è disponibile anche in italiano.', 'Leggi in italiano', 'Chiudi'],
    'nl': ['Deze pagina is ook beschikbaar in het Nederlands.', 'Lees in het Nederlands', 'Sluiten'],
    'id': ['Halaman ini juga tersedia dalam Bahasa Indonesia.', 'Baca dalam Bahasa Indonesia', 'Tutup'],
    'tr': ['Bu sayfa Türkçe olarak da mevcut.', 'Türkçe oku', 'Kapat'],
    'pl': ['Ta strona jest dostępna również po polsku.', 'Czytaj po polsku', 'Zamknij'],
    'ja': ['このページは日本語でもご覧いただけます。', '日本語で読む', '閉じる'],
    'ko': ['이 페이지는 한국어로도 제공됩니다.', '한국어로 보기', '닫기'],
    'zh-tw': ['本頁面也提供繁體中文版本。', '閱讀繁體中文版', '關閉']
  };
  // header language menu (<details class="i18n-menu">): close on outside click and Escape
  document.addEventListener('click', function (e) {
    var open = document.querySelectorAll('details.i18n-menu[open]');
    for (var n = 0; n < open.length; n++) { if (!open[n].contains(e.target)) open[n].removeAttribute('open'); }
  });
  // A header nav that does not wrap can push the menu off-screen or hide it on phones (the nav
  // overflows, or the site hides it). Then the menu moves to the page's top-right corner; a comment
  // placeholder remembers its header spot so it can go back when the viewport grows.
  // A top-right pill must not cover header text (e.g. a long breadcrumb on a phone): if it does,
  // the page gets just enough top padding for the pill to sit above the content.
  var body = document.body;
  var basePad = null;
  function clearOverlap(m) {
    var r = m.getBoundingClientRect();
    var els = document.querySelectorAll('header *, .header-bar *, .site-nav *');
    for (var k = 0; k < els.length; k++) {
      var e = els[k];
      if (m.contains(e) || e.children.length) continue;
      var q = e.getBoundingClientRect();
      if (q.width && q.height && q.right > r.left && q.left < r.right && q.bottom > r.top && q.top < r.bottom) {
        if (basePad === null) basePad = body.style.paddingTop;
        var pt = parseFloat(getComputedStyle(body).paddingTop) || 0;
        body.style.paddingTop = (pt + (r.bottom - q.top) + 8) + 'px';
        return;
      }
    }
  }
  function fitMenus() {
    var vw = document.documentElement.clientWidth || window.innerWidth;
    if (basePad !== null) { body.style.paddingTop = basePad; basePad = null; }
    var menus = document.querySelectorAll('details.i18n-menu');
    for (var n = 0; n < menus.length; n++) {
      var m = menus[n];
      if (m.__i18nHome) {
        m.__i18nHome.parentNode.insertBefore(m, m.__i18nHome);
        m.classList.remove('i18n-menu--float');
      } else if (m.classList.contains('i18n-menu--float')) {
        continue;
      }
      var r = m.getBoundingClientRect();
      if (m.offsetParent === null || r.width === 0 || r.left < 0 || r.right > vw + 1) {
        if (!m.__i18nHome) {
          m.__i18nHome = document.createComment('i18n-menu');
          m.parentNode.insertBefore(m.__i18nHome, m);
        }
        m.classList.add('i18n-menu--float');
        document.body.appendChild(m);
      }
    }
    var floats = document.querySelectorAll('details.i18n-menu--float');
    for (var f = 0; f < floats.length; f++) clearOverlap(floats[f]);
  }
  fitMenus();
  window.addEventListener('load', fitMenus);
  var fitTimer = null;
  window.addEventListener('resize', function () { clearTimeout(fitTimer); fitTimer = setTimeout(fitMenus, 150); });
  // keep the opened list on screen: right-aligned by default, flipped left when the pill sits
  // near the left edge (e.g. a stacked mobile nav)
  document.addEventListener('toggle', function (e) {
    var d = e.target;
    if (!d || !d.classList || !d.classList.contains('i18n-menu') || !d.open) return;
    var ul = d.querySelector('ul');
    if (!ul) return;
    ul.style.left = ''; ul.style.right = '';
    var r = ul.getBoundingClientRect();
    var vw = document.documentElement.clientWidth || window.innerWidth;
    if (r.left < 8) { ul.style.left = '0'; ul.style.right = 'auto'; }
    else if (r.right > vw - 8) { ul.style.right = '0'; ul.style.left = 'auto'; }
  }, true);
  document.addEventListener('keydown', function (e) {
    if (e.key !== 'Escape') return;
    var open = document.querySelectorAll('details.i18n-menu[open]');
    for (var n = 0; n < open.length; n++) {
      open[n].removeAttribute('open');
      var s = open[n].querySelector('summary');
      if (s) s.focus();
    }
  });
  function store(v) { try { window.localStorage.setItem(KEY, v); } catch (e) {} }
  function stored() { try { return window.localStorage.getItem(KEY); } catch (e) { return null; } }
  document.addEventListener('click', function (e) {
    var a = e.target && e.target.closest ? e.target.closest('a[data-i18n-lang]') : null;
    if (a) store(a.getAttribute('data-i18n-lang'));
  });
  if (stored()) return;
  var cur = (document.documentElement.getAttribute('lang') || 'en').toLowerCase();
  var alts = {};
  var links = document.querySelectorAll('link[rel="alternate"][hreflang]');
  for (var i = 0; i < links.length; i++) {
    var h = (links[i].getAttribute('hreflang') || '').toLowerCase();
    if (h && h !== 'x-default') alts[h] = links[i].href;
  }
  var prefs = navigator.languages && navigator.languages.length ? navigator.languages : [navigator.language || ''];
  var target = null;
  for (var j = 0; j < prefs.length && !target; j++) {
    var p = String(prefs[j] || '').toLowerCase();
    var base = p.split('-')[0];
    if (!base) continue;
    if (p === cur || base === cur.split('-')[0]) return;
    if (alts[p]) { target = p; break; }
    for (var k in alts) { if (k.split('-')[0] === base) { target = k; break; } }
  }
  if (!target || !MSG[target] || !alts[target]) return;
  var m = MSG[target];
  var bar = document.createElement('div');
  bar.setAttribute('role', 'region');
  bar.setAttribute('lang', target);
  bar.setAttribute('translate', 'no');
  bar.style.cssText = 'position:fixed;left:12px;right:12px;bottom:12px;max-width:560px;margin:0 auto;' +
    'z-index:2147483000;background:#111827;color:#f9fafb;border:1px solid #374151;border-radius:10px;' +
    'padding:10px 14px;font:14px/1.4 system-ui,-apple-system,Segoe UI,sans-serif;display:flex;gap:12px;' +
    'align-items:center;box-shadow:0 8px 24px rgba(0,0,0,.35)';
  var txt = document.createElement('span');
  txt.style.flex = '1';
  txt.textContent = m[0] + ' ';
  var go = document.createElement('a');
  go.href = alts[target];
  go.textContent = m[1];
  go.setAttribute('data-i18n-lang', target);
  go.style.cssText = 'color:#93c5fd;font-weight:600;text-decoration:underline';
  txt.appendChild(go);
  var close = document.createElement('button');
  close.type = 'button';
  close.setAttribute('aria-label', m[2]);
  close.textContent = '\u00d7';
  close.style.cssText = 'background:none;border:0;color:#9ca3af;font-size:20px;line-height:1;cursor:pointer;padding:0 4px';
  close.addEventListener('click', function () { store(cur); bar.parentNode && bar.parentNode.removeChild(bar); });
  bar.appendChild(txt);
  bar.appendChild(close);
  document.body.appendChild(bar);
})();
